# A docker-compose must always start by the version tag.
# We use "3.9" because it's the last version at this time.
version: "3.9"


networks:
  onkolos:
    name: onkolos
    driver: bridge
    



# You should know that docker-composes works with services.

#####################################################################
#          Onkolos data server services                             #
#####################################################################
###file:///home/sopka/onkolos/server-data-analytics/dockers/hive-metastore
#services:
  #hive-metastore:
  #  container_name: hive-metastore
  #  build:
  #    context: dockers/hive-metastore/.
  #    dockerfile: Dockerfile
  #    args:
  #      BUILD_VERSION: ${BUILD_VERSION}
  #  env_file: ./configs
  #  image: hive-metastore
  #  logging:
  #    driver: "json-file"
  #  networks:
  #    - onkolos
  # to create: a data server.
  # That is any services.
  
    #container_name: 
    #image:
    #hostname: 
    #ports:      
    #environment:
    #volumes:
    #restart: unless-stopped
    #command:
    #configs:
    #depends_on:
    #logging:
    #    options:
    #      max-size: 1000m
    #networks:
    #  - onkolos

